# Generated by Django 5.1.2 on 2024-10-27 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato 99999-999.', regex='^\\d{5}-\\d{3}$')])),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('responsavel_tecnico', models.CharField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no formato (99) 99999-9999 ou (99) 9999-9999.', regex='^\\(?\\d{2}\\)? ?9?\\d{4}-\\d{4}$')])),
            ],
        ),
    ]
