# Generated by Django 5.1.2 on 2024-10-27 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter apenas dígitos e ter 10 ou 11 dígitos.', regex='^\\d{10,11}$')]),
        ),
    ]
