# Generated by Django 5.1.2 on 2024-11-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio', '0002_escritorio_complemento_alter_escritorio_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
