# Generated by Django 5.1.2 on 2024-12-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoes',
            name='cores',
            field=models.TextField(blank=True, null=True),
        ),
    ]
