# Generated by Django 5.1.2 on 2024-12-26 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_configuracoes_cores'),
        ('escritorio', '0004_escritorio_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracoes',
            old_name='cores',
            new_name='cor_principal',
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='empresa_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escritorio.escritorio'),
            preserve_default=False,
        ),
    ]
