# Generated by Django 5.1.2 on 2024-12-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_rename_cores_configuracoes_cor_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoes',
            name='email_notificacao',
            field=models.EmailField(default='email@email.com', max_length=100),
        ),
    ]
