# Generated by Django 5.1.2 on 2024-12-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0004_configuracoes_email_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoes',
            name='envia_notificacao',
            field=models.BooleanField(default=False),
        ),
    ]
