# Generated by Django 5.1.2 on 2024-12-09 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('escritorio', '0004_escritorio_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='escritorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='escritorio.escritorio'),
        ),
    ]
