# Generated by Django 5.1.2 on 2024-11-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_delete_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='regime_fiscal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
