# Generated by Django 5.1.2 on 2024-11-06 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_regime_fiscal_cliente_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimeFiscal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='regime_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regime_fiscal', to='clientes.regimefiscal'),
        ),
    ]
