# Generated by Django 5.1.2 on 2024-11-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_regimefiscal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_exclusao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_inclusao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
