# Generated by Django 5.1.2 on 2024-11-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_data_exclusao_cliente_data_inclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_exclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_inclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
