# Generated by Django 5.1.2 on 2024-12-05 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_remove_consultahistorico_detalhes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultahistorico',
            name='status',
        ),
    ]
