# Generated by Django 5.1.2 on 2024-12-05 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_remove_consultahistorico_status'),
        ('escritorio', '0004_escritorio_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultahistorico',
            name='escritorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escritorio_historico', to='escritorio.escritorio'),
        ),
    ]
