# Generated by Django 5.1.2 on 2024-12-05 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_consultahistorico_escritorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultahistorico',
            name='porte_empresa',
        ),
        migrations.AddField(
            model_name='consultahistorico',
            name='data_exclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultahistorico',
            name='data_inclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultahistorico',
            name='tipo_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_empresa_historico', to='clientes.tipoempresa'),
        ),
    ]
