# Generated by Django 5.1.2 on 2024-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_remove_consultahistorico_porte_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultahistorico',
            name='tipo_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Empresa'),
        ),
    ]
